README for CellBlender and MCell Tutorials

The CellBlender and MCell tutorials located at
http://www.mcell.psc.edu/tutorials/ are generated using Sphinx
(http://sphinx-doc.org/index.html). If Sphinx is installed, the html files can
be generated by using the command "make html" in this directory.

Some of the binary files are not stored in the repo to keep the size of it
small, but that policy will likely change if more collaborators need to
contribute images, blend files, etc.

Here are some basic steps to begin contributing to the "CellBlender and MCell
Tutorials" repository:

* Read this page to develop a basic understanding of ReST syntax:
  http://sphinx-doc.org/rest.html
    * The official "quick start" guide:
      http://docutils.sourceforge.net/docs/user/rst/quickstart.html
    * The official reference guide:
      http://docutils.sourceforge.net/docs/user/rst/quickref.html
    * Sphinx specific syntax: http://sphinx-doc.org/markup/index.html
* Install sphinx on your local machine.
* Follow this tutorial, which will briefly explain how Sphinx projects work:
  http://sphinx-doc.org/tutorial.html
* Once you finish the previous tutorial, you are free to delete the project
  directory that they have you create (if you want).
* Pull the CellBlender tutorial from the github repository
  (https://github.com/jczech/cellblender_tutorials.git).
    * The repostiory itself is a Sphinx project made up of various ReST files
      and Sphinx configuration files (e.g conf.py).
    * You shouldn't have to do another "sphinx-quickstart".
    * Simply edit the ReST files locally as needed.
    * Each ReST file will create a corresponding HTML file.
    * If you add a completely new ReST file, make sure you add it to
      the table of content tree (toctree) in "index.rst"
    * When you're ready to see your changes, type "make html".
    * A status message will tell you if creating the html was successful.
    * From the repo directory, change into "./_build/html/" and open index.html
      with your browser of choice.
    * If you're satisfied with how the new html looks, push it to the github
      repository (assuming you have permissions).
        * The "_build" directory will not be pushed, since it is in the
          ".gitignore" file.
